### ISSUE TITLE
SQL error with cassandra 3.7

### ISSUE THREAD

**Issue by martinscheffler** [Contrast-Security-OSS/cassandra-migration#32]
In SchemaVersionDAO.java, line 205, 
" SET count = count + 1" +
"WHERE name = 'installed_rank';");

there is a missing whitespace between "1" and "WHERE". This starts to cause exceptions from cassandra 3.7 on, no idea why it was accepted before

**Comment by alexis-morillo** [comment]
I have exactly the same issue with cassandra 3.10 :
`Caused by: com.datastax.driver.core.exceptions.SyntaxError: line 1:86 no viable alternative at input 'HERE' (... count = count + 1W[HERE]...)
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:58)
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:24)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
	at com.contrastsecurity.cassandra.migration.dao.SchemaVersionDAO.calculateInstalledRank(SchemaVersionDAO.java:207)
	at com.contrastsecurity.cassandra.migration.dao.SchemaVersionDAO.addAppliedMigration(SchemaVersionDAO.java:135)
	at com.contrastsecurity.cassandra.migration.action.Migrate.applyMigration(Migrate.java:126)
	at com.contrastsecurity.cassandra.migration.action.Migrate.run(Migrate.java:83)
	at com.contrastsecurity.cassandra.migration.CassandraMigration$1.execute(CassandraMigration.java:77)
	at com.contrastsecurity.cassandra.migration.CassandraMigration$1.execute(CassandraMigration.java:68)
	at com.contrastsecurity.cassandra.migration.CassandraMigration.execute(CassandraMigration.java:174)
	at com.contrastsecurity.cassandra.migration.CassandraMigration.migrate(CassandraMigration.java:68)
`

**Comment by luiseduardomiranda** [comment]
+1
